# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e1f1e4e46917facf894bce11507e2d5fb780cca63e1eaa53c4af65aa08477c923b9e491676c2f440bc23eacb8a7e857f0f695c0c5625d1f7771a79c1e7542da

test:
  secret_key_base: edb38f723aa86655ec8781bdffc474c12b0e277ef71f073169ca846d22c9c53902437f803d8b07f0def6c4aa98f40f0edd63d66ea07269a21c5391775baa3c91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
